import { Inter } from "next/font/google";
import "./globals.css";
import { UserContextProvider } from "./context/userContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "WhatsApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserContextProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </UserContextProvider>
  );
}
